// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {controller} from '../models';
import {context} from '../models';

export function AddFolderImage(arg1:models.Folder):Promise<models.Folder>;

export function AllFolderImage():Promise<Array<models.Folder>>;

export function Carpet():Promise<string>;

export function Images():Promise<Array<controller.ImagesRouteBase64>>;

export function Startup(arg1:context.Context):Promise<void>;

export function TransferImageToFolder(arg1:string,arg2:string,arg3:string):Promise<models.JsonResponse>;

export function TransferImages(arg1:string,arg2:string):Promise<void>;
