// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolderImage(arg1) {
  return window['go']['controller']['Image']['AddFolderImage'](arg1);
}

export function AllFolderImage() {
  return window['go']['controller']['Image']['AllFolderImage']();
}

export function Carpet() {
  return window['go']['controller']['Image']['Carpet']();
}

export function Images() {
  return window['go']['controller']['Image']['Images']();
}

export function Startup(arg1) {
  return window['go']['controller']['Image']['Startup'](arg1);
}

export function TransferImageToFolder(arg1, arg2, arg3) {
  return window['go']['controller']['Image']['TransferImageToFolder'](arg1, arg2, arg3);
}

export function TransferImages(arg1, arg2) {
  return window['go']['controller']['Image']['TransferImages'](arg1, arg2);
}
