// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ImageUrl(arg1:string,arg2:string):Promise<string>;

export function ImageUrlList(arg1:Array<string>,arg2:Array<string>):Promise<Array<string>>;

export function ReturnImage():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
