// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImageUrl(arg1, arg2) {
  return window['go']['controller']['Qr']['ImageUrl'](arg1, arg2);
}

export function ImageUrlList(arg1, arg2) {
  return window['go']['controller']['Qr']['ImageUrlList'](arg1, arg2);
}

export function ReturnImage() {
  return window['go']['controller']['Qr']['ReturnImage']();
}

export function Startup(arg1) {
  return window['go']['controller']['Qr']['Startup'](arg1);
}
